services:
  postgres:
    image: docker.io/library/postgres:13.4
    command: [-cmax_prepared_transactions=100]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      # POSTGRES_DB: postgres
      # POSTGRES_USER: postgres
    volumes:
      - ./dc/db:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - example

  keycloak-private:
    image: quay.io/keycloak/keycloak:23.0.4
    command: "start-dev --import-realm"
    ports:
      - "8083:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_POOL_INITIAL_SIZE : 1
      KC_DB_POOL_MAX_SIZE : 5
      KC_DB_POOL_MIN_SIZE : 2
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: keycloak-app
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_HTTP_PORT: 8080
      KC_HEALTH_ENABLED: true
    volumes:
      - ./dc/keycloak/imports:/opt/keycloak/data/import
    healthcheck:
      test: "{ printf >&3 'GET /realms/onecx/.well-known/openid-configuration HTTP/1.0\r\nHost: localhost\r\n\r\n'; cat <&3; } 3<>/dev/tcp/localhost/8080 | head -1 | grep 200"
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - example

  keycloak-public:
    image: quay.io/keycloak/keycloak:23.0.4
    command: "start-dev --import-realm"
    ports:
      - "8084:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_POOL_INITIAL_SIZE : 1
      KC_DB_POOL_MAX_SIZE : 5
      KC_DB_POOL_MIN_SIZE : 2
      KC_DB_URL_DATABASE: keycloak_public
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak_public
      KC_DB_PASSWORD: keycloak_public
      KC_HOSTNAME: keycloak-public
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_HTTP_PORT: 8080
      KC_HEALTH_ENABLED: true
    volumes:
      - ./dc/keycloak/imports:/opt/keycloak/data/import
    healthcheck:
      test: "{ printf >&3 'GET /realms/onecx/.well-known/openid-configuration HTTP/1.0\r\nHost: localhost\r\n\r\n'; cat <&3; } 3<>/dev/tcp/localhost/8080 | head -1 | grep 200"
      interval: 15s
      timeout: 10s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - example

networks:
  example: