= 1000kit Quarkus Extensions

include::./includes/attributes.adoc[]

== Installation

Include the following bom artifact into your pom or parent pom and then pick the components you need.

[source,xml,subs=attributes+]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.tkit.quarkus.lib</groupId>
            <artifactId>tkit-quarkus-bom</artifactId>
            <version>{project-version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

TIP: Some component come with additional documentation and configuration - check the 'Documentation' link for particular section.

== Components

Include the component in your project by including the corresponding dependency.

* xref:tkit-quarkus-context.adoc[Context]
* xref:tkit-quarkus-data-import.adoc[Master Data Import]
* xref:tkit-quarkus-db-import.adoc[Test Database Import]
* xref:tkit-quarkus-jpa.adoc[JPA Persistence]
* xref:tkit-quarkus-jpa-models.adoc[JPA Persistence Models]
* xref:tkit-quarkus-jpa-tenant.adoc[JPA Persistence Tenant Resolver]
* xref:tkit-quarkus-log-cdi.adoc[CDI Log Interceptor]
* xref:tkit-quarkus-log-json.adoc[Json Log Format]
* xref:tkit-quarkus-log-rs.adoc[Rest Log Interceptor]
* xref:tkit-quarkus-rest.adoc[Rest Extension]
* xref:tkit-quarkus-rest-context.adoc[Rest Context Extension]
* xref:tkit-quarkus-security.adoc[Rest Security]