== tkit-quarkus-security-test

include::./includes/attributes.adoc[]

The `tkit-quarkus-security-test` is a testing extension for the Quarkus framework designed to enhance security testing. It integrates security validation in Quarkus-based applications by providing automated OpenAPI security tests. To use the extension, you need to add it as a dependency in your Maven project.
Key features:

* It allows the registration and execution of security tests through QuarkusIntegrationTest.
* It enables automated testing of security policies such as OAuth2 integration via Keycloak clients generated through annotations.
* Custom configurations let users enable/disable tests based on project specifics.

This tool helps automate security validation and integrates smoothly with Quarkus applications for secure testing workflows.

=== Installation

If you want to use this extension, you need to add the `org.tkit.quarkus.lib:tkit-quarkus-security-test` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>org.tkit.quarkus.lib</groupId>
    <artifactId>tkit-quarkus-security-test</artifactId>
    <version>{project-version}</version>
    <scope>test</scope>
</dependency>
----

=== Usage

To work in `@QuarkusIntegrationTest` tests set the property `quarkus.test.enable-callbacks-for-integration-tests = true` in your application.properties.


=== OpenAPI Security Tests

To registry default security tests you need to add this library to the `maven-surefire-plugin` class-path.

[source,xml,subs=attributes+]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <configuration>
        <dependenciesToScan>
            <dependency>org.tkit.quarkus.lib:tkit-quarkus-security-test</dependency>
        </dependenciesToScan>
    </configuration>
</plugin>
----

This will start `org.tkit.quarkus.security.test.openapi.SecurityDynamicTest` be default.


To run this test as an integration test, you need to add this class to your project:

[source,java,subs=attributes+]
----
import io.quarkus.test.junit.QuarkusIntegrationTest;

@QuarkusIntegrationTest
public class SecurityDynamicTestIT extends SecurityDynamicTest {

}
----

This test can be disabled if the value of the system property `tkit.security-test.openapi.disable-value` matches the regular expression of the system property `tkit.security-test.openapi.disable-regex`.

For example, this test is only disabled for projects with the prefix `E`.

[source,xml,subs=attributes+]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <configuration>
        <systemPropertyVariables>
            <tkit.security-test.openapi.disable-value>${project.artifactId}</tkit.security-test.openapi.disable-value>
            <tkit.security-test.openapi.disable-regex>E.*</tkit.security-test.openapi.disable-regex>
        </systemPropertyVariables>
    </configuration>
</plugin>
----

=== Generate Keycloak clients via annotation

==== Class Level
Generated for all test methods in this class

[source,java]
----
@GenerateKeycloakClient(clientName = "testClient", scopes = { "ocx-user:read", "ocx-user:write" })
public class UserRestControllerTest {
    @Test
    public void testUserRestClient() {
        given().header("Content-Type", "application/json")
                .auth().oauth2(getKeycloakClientToken("testClient"))
                .get("/1")
                .then()
                .statusCode(Response.Status.OK.getStatusCode());
    }
}

----

=== Configuration

include::includes/tkit-quarkus-security-test.adoc[leveloffset=+1, opts=optional]