== tkit-quarkus-rest

include::./includes/attributes.adoc[]

This extension contains `OffsetDateTimeMapper` Jackson DateTimeOffset convertor for path and body parameters. The `RegisterCustomModuleCustomizer` update Jackson configuration to write `date-time` as string.

=== Installation

If you want to use this extension, you need to add the `org.tkit.quarkus.lib:tkit-quarkus-rest` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>org.tkit.quarkus.lib</groupId>
    <artifactId>tkit-quarkus-rest</artifactId>
    <version>{project-version}</version>
</dependency>
----
=== Configuration

[cols="2,1,7"]
|===
|Configuration property |Default |Description

|`tkit.rs.response.propagation.headers`
|`[]`
|List of HTTP headers to propagate from request to response. When specified, the `HeaderResponsePropagationFilter` will copy these headers from the incoming request to the outgoing response. Only headers that are present in the request and match the names in this list will be propagated. By default, no headers are propagated. +
*Example:* `tkit.rs.response.propagation.headers=X-Business-Context,X-Correlation-ID`
|===
