== tkit-quarkus-metrics-test
include::./includes/attributes.adoc[]


Metrics test configuration

=== Installation

If you want to use this extension, you need to add the `org.tkit.quarkus.lib:tkit-quarkus-metrics-test` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>org.tkit.quarkus.lib</groupId>
    <artifactId>tkit-quarkus-metrics-test</artifactId>
    <version>{project-version}</version>
    <scope>test</scope>
</dependency>
----

=== Usage

To work in @QuarkusIntegrationTest tests set the property

**quarkus.test.enable-callbacks-for-integration-tests = true**

in your application.properties.


To deactivate the automated metrics tests use

*-Dtkit.metrics-test.disabled=true* as system property

e.g.
*mvn clean verify -Dtkit.metrics-test.disabled=true*


=== Metrics Tests

To registry default metrics tests you need to add this library to the `maven-surefire-plugin` class-path.

[source,xml,subs=attributes+]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <configuration>
        <systemPropertyVariables>
            <tkit.metrics-test.keys.quarkus.datasource>agroal_awaiting_count,agroal_max_used_count,agroal_creation_time_max_milliseconds,agroal_destroy_count_total</tkit.metrics-test.keys.quarkus.datasource>
            <tkit.metrics-test.keys.quarkus.hibernate-orm>hibernate_transactions_total,hibernate_query_executions_total</tkit.metrics-test.keys.quarkus.hibernate-orm>
            <tkit.metrics-test.keys.quarkus.http>http_server_requests_seconds_count,http_server_requests_seconds_max</tkit.metrics-test.keys.quarkus.http>
            <tkit.metrics-test.keys.quarkus.rest-client>http_client_requests_seconds_count,http_client_requests_seconds_max</tkit.metrics-test.keys.quarkus.rest-client>
        </systemPropertyVariables>
        <dependenciesToScan>
            <dependency>org.tkit.quarkus.lib:tkit-quarkus-metrics-test</dependency>
        </dependenciesToScan>
    </configuration>
</plugin>
----

This will start `org.tkit.quarkus.metrics.test.MetricsDynamicTest` be default.

In this example, we also enable some metrics. For example `<tkit.metrics-test.keys.quarkus.hibernate-orm>` configuration. If the test finds a system property that starts with a `quarkus.hibernate-orm`, `hibernate_transactions_total` metric is mandatory, and if the test does not find this metric key, it fails.

To run this test as an integration test, you need to add this class to your project:

[source,java,subs=attributes+]
----
import io.quarkus.test.junit.QuarkusIntegrationTest;
import org.tkit.quarkus.metrics.test.MetricsDynamicTest;

@QuarkusIntegrationTest
public class MetricsDynamicTestIT extends MetricsDynamicTest {

}
----

=== Configuration

include::includes/tkit-quarkus-metrics-test.adoc[leveloffset=+1, opts=optional]