== tkit-quarkus-security-test

include::./includes/attributes.adoc[]

Enhanced security configuration

=== Installation

If you want to use this extension, you need to add the `org.tkit.quarkus.lib:tkit-quarkus-security-test` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>org.tkit.quarkus.lib</groupId>
    <artifactId>tkit-quarkus-security-test</artifactId>
    <version>{project-version}</version>
    <scope>test</scope>
</dependency>
----

=== Usage

To work in @QuarkusIntegrationTest tests set the property

**quarkus.test.enable-callbacks-for-integration-tests = true**

in your application.properties.


To deactivate the automated security tests of AbstractSecurityTests use

*-Dtkit.security-test.disabled=true* as system property

e.g.
*mvn clean verify -Dtkit.security-test.disabled=true*


=== OpenAPI Security Tests

To registry default security tests you need to add this library to the `maven-surefire-plugin` class-path.

[source,xml,subs=attributes+]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <configuration>
        <dependenciesToScan>
            <dependency>org.tkit.quarkus.lib:tkit-quarkus-security-test</dependency>
        </dependenciesToScan>
    </configuration>
</plugin>
----

This will start `org.tkit.quarkus.security.test.openapi.SecurityDynamicTest` be default.


=== Generate Keycloak clients via annotation

==== Class Level
Generated for all test methods in this class

[source,java]
----
@GenerateKeycloakClient(clientName = "testClient", scopes = { "ocx-user:read", "ocx-user:write" })
public class UserRestControllerTest {
    @Test
    public void testUserRestClient() {
        given().header("Content-Type", "application/json")
                .auth().oauth2(getKeycloakClientToken("testClient"))
                .get("/1")
                .then()
                .statusCode(Response.Status.OK.getStatusCode());
    }
}

----

==== Method Level
Generated for the annotated method

[source,java]
----
    @Test
    @GenerateKeycloakClient(clientName = "methodLevelClient", scopes = { "ocx-user:read", "ocx-user:write" })
    public void testCreateUserRestClient() {
        given().header("Content-Type", "application/json")
                .body("{\"id\":\"2\"}")
                .auth().oauth2(getKeycloakClientToken("methodLevelClient"))
                .post("/2")
                .then()
                .statusCode(Response.Status.OK.getStatusCode());
    }

----

=== Configuration

include::includes/tkit-quarkus-security-test.adoc[leveloffset=+1, opts=optional]