== tkit-quarkus-data-import

include::./includes/attributes.adoc[]

1000kit quarkus data import extension during the start of the application.

=== Installation

If you want to use this extension, you need to add the `org.tkit.quarkus.lib:tkit-quarkus-data-import` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>org.tkit.quarkus.lib</groupId>
    <artifactId>tkit-quarkus-data-import</artifactId>
    <version>{project-version}</version>
</dependency>
----

=== Usage

The log of the data import changes is stored in the `dataimportlog` table. To create this table copy and paste these liquibase changes to your project.
[source,xml]
----
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
                   xmlns:pro="http://www.liquibase.org/xml/ns/pro"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-3.8.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd"
                   objectQuotingStrategy="QUOTE_ONLY_RESERVED_WORDS">
    <changeSet author="dev (generated)" id="dataimportlog-1">
        <createTable tableName="dataimportlog">
            <column name="id" type="VARCHAR(255)">
                <constraints nullable="false" primaryKey="true" primaryKeyName="dataimportlog_pkey"/>
            </column>
            <column name="creationdate" type="TIMESTAMP WITHOUT TIME ZONE"/>
            <column name="modificationdate" type="TIMESTAMP WITHOUT TIME ZONE"/>
            <column name="file" type="VARCHAR(255)"/>
            <column name="md5" type="VARCHAR(255)"/>
            <column name="error" type="VARCHAR(255)"/>
        </createTable>
    </changeSet>
</databaseChangeLog>
----

Or embedded it in the project from file xref:../../../../extensions/data-import/runtime/src/main/resources/db/create-log-table.xml[create-log-table]
[source,xml]
----
<include file="classpath:/db/create-log-table.xml"/>
----
Example embedded configuration xref:../../../../extensions/data-import/tests/src/main/resources/db/changeLog.xml[changelog.xml]

Flyway sql script:
[source,sql]
----
CREATE TABLE DATAIMPORTLOG (
    ID VARCHAR(255) NOT NULL,
    CREATIONDATE TIMESTAMP WITHOUT TIME ZONE,
    MODIFICATIONDATE TIMESTAMP WITHOUT TIME ZONE,
    FILE VARCHAR(255),
    MD5 VARCHAR(255),
    ERROR VARCHAR(255),
    CONSTRAINT DATAIMPORTLOG_PKEY PRIMARY KEY (ID)
);
----

Create bean with `@DataImport("my-import-key")` bean which implements the `DataImportService` interface.
Example bean xref:../../../../extensions/data-import/tests/src/main/java/org/tkit/quarkus/dataimport/test/ParameterTestImport.java[ParameterTestImport]
[source,java]
----
@DataImport("my-import-key")
public class ParameterTestImport implements DataImportService {

    @Inject MyModelDAO dao;
    @Inject ObjectMapper mapper;

    @Override
    public void importData(DataImportConfig config) {
        try {
            MyModel model = mapper.readValue(config.getData(), MyModel.class);
            dao.create(model);
        } catch (Exception ex) {
            throw new RuntimeException("Error import", ex);
        }
    }
}
----

Example configuration
[source,properties]
----
tkit.dataimport.enabled=true
tkit.dataimport.configurations.key1.file=/data/example_data.json
tkit.dataimport.configurations.key1.metadata.operation=UPDATE
tkit.dataimport.configurations.key1.metadata.check=FALSE
tkit.dataimport.configurations.key1.enabled=true
tkit.dataimport.configurations.key1.stop-at-error=false
----

=== Configuration

include::includes/tkit-quarkus-data-import.adoc[leveloffset=+1, opts=optional]