name: build
on:
  push:
    branches:
      - 'main'
      - 'fix/[0-9]+.[0-9]+.x'
      - '[0-9]+.x'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'main'
      - 'fix/[0-9]+.[0-9]+.x'
      - '[0-9]+.x'
jobs:
  java:
    uses: 1000kit/tkit-ci-java/.github/workflows/build.yml@main
    secrets: inherit
